paths:
  /products:
    get:
      summary: Obtiene todos los productos paginados, 4 por página
      tags:
        - Products
      responses:
        200:
          description: Los productos fueron obtenidos exitosamente desde la base de datos.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
        500:
          description: Error interno del servidor.
    post:
      summary: Permite crear un producto.
      tags:
        - Products
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/requestBodies/createProduct'
      responses:
        200:
          description: Producto creado en la base de datos.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        403:
          description: No tienes permiso para crear productos
        500:
          description: Error interno del servidor.

  /products/{pid}:
    get:
      summary: Permite obtener un producto por su identificador.
      tags:
        - Products
      parameters:
        - in: path
          name: pid
          required: true
          description: Identificador del producto.
          schema:
            type: string
      responses:
        200:
          description: Producto encontrado en la base de datos.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        401:
          description: Producto con id no encontrado.
        500:
          description: Error interno del servidor.
    put:
      summary: Permite actualizar un producto por su identificador.
      tags:
        - Products
      parameters:
        - in: path
          name: pid
          required: true
          description: Identificador del producto.
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/requestBodies/updateProduct'
      responses:
        200:
          description: Producto actualizado en la base de datos.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        404:
          description: Producto no encontrado.
        500:
          description: Error interno del servidor.
    delete:
      summary: Elimina un producto por su ID
      tags:
        - Products
      parameters:
        - in: path
          name: pid
          required: true
          description: ID del producto
          schema:
            type: string
      responses:
        200:
          description: Producto eliminado
        404:
          description: Producto no encontrado
        500:
          description: Error interno del servidor      
    
  

components:
  schemas:
    Product:
      type: object
      properties:
        _id:
          type: string
          description: ID del producto
        title:
          type: string
          description: Nombre del producto
        description:
          type: string
          description: Descripción del producto
        code:
          type: string
          description: Código único de un producto
        price:
          type: integer
          description: Precio del producto
        status:
          type: boolean
          description: En caso de ser true el producto se encuentra activo
        stock:
          type: number
          description: Stock del producto al momento de realizar la consulta
        category:
          type: string
          description: Categoria a la que pertenece el producto
        thumbnails:
          type: string
          description: Link a las imágenes
        owner:
          type: string
          description: Id del dueño del producto, si no posee por defecto se asigna un admin con id 65db84bbc412c75b8df481a9
      example:
        _id: 65db8491bcdb27b1b34f8e3d
        title: Red Graphite
        description: Este reloj ultrafino de acero inoxidable tiene un estilo atemporal. El acero pulido de este elegante reloj realza la esfera negra satinada con estampados rojos y detalles de Swatch plateados. El elegante brazalete incluye una hebilla con forma de mariposa.
        price: 104.995
        status: true
        stock: 94
        category: Hombres
        thumbnails: https://static.swatch.com/images/product/SS07S129G/sa200/SS07S129G_sa200_er005.png
        owner: 65db84bbc412c75b8df481a9
  
  requestBodies:
    createProduct:
      type: object
      properties:
        _id:
          type: string
          description: ID del producto
        title:
          type: string
          description: Nombre del producto
        description:
          type: string
          description: Descripción del producto
        code:
          type: string
          description: Código único de un producto
        price:
          type: integer
          description: Precio del producto
        status:
          type: boolean
          description: En caso de ser true el producto se encuentra activo
        stock:
          type: number
          description: Stock del producto al momento de realizar la consulta
        category:
          type: string
          description: Categoria a la que pertenece el producto
        thumbnails:
          type: string
          description: Link a las imágenes
        owner:
          type: string
          description: Id del dueño del producto, si no posee por defecto se asigna un admin con id 65db84bbc412c75b8df481a9
      example:
        title: Red Graphite
        description: Este reloj ultrafino de acero inoxidable tiene un estilo atemporal. El acero pulido de este elegante reloj realza la esfera negra satinada con estampados rojos y detalles de Swatch plateados. El elegante brazalete incluye una hebilla con forma de mariposa.
        code: abc1
        price: 104.995
        status: true
        stock: 94
        category: Hombres
        thumbnails: url
        owner: 65db84bbc412c75b8df481a9
    updateProduct:
      type: object
      properties:
        _id:
          type: string
          description: ID del producto
        title:
          type: string
          description: Nombre del producto
        description:
          type: string
          description: Descripción del producto
        code:
          type: string
          description: Código único de un producto
        price:
          type: integer
          description: Precio del producto
        status:
          type: boolean
          description: En caso de ser true el producto se encuentra activo
        stock:
          type: number
          description: Stock del producto al momento de realizar la consulta
        category:
          type: string
          description: Categoria a la que pertenece el producto
        thumbnails:
          type: string
          description: Link a las imágenes
        owner:
          type: string
          description: Id del dueño del producto, si no posee por defecto se asigna un admin con id 65db84bbc412c75b8df481a9
      example:
        title: Chicken
        description: Carbonite web goalkeeper gloves are ergonomically designed to give easy fit
        code: d5b14d3f-eb86-4fea-9122-ab6603c67998
        price: 50
        status: true
        stock: 235
        category: Food
        thumbnails: hola
        owner: 65db84bbc412c75b8df481a9